// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ŽVPAIS_API.Data;

#nullable disable

namespace ŽVPAIS_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512120000_SeedMissingMaterialsAndObjects")]
    partial class SeedMissingMaterialsAndObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ŽVPAIS_API.Models.DamageEvaluation", b =>
                {
                    b.Property<int>("IdDamageEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_damage_evaluation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDamageEvaluation"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_event");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<double?>("PiniginisDydis")
                        .HasColumnType("double precision")
                        .HasColumnName("piniginis_dydis");

                    b.Property<double?>("ZalosDydis")
                        .HasColumnType("double precision")
                        .HasColumnName("zalos_dydis");

                    b.HasKey("IdDamageEvaluation");

                    b.HasIndex("EventId");

                    b.ToTable("damage_evaluations");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EmissionCompound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("BaseRate")
                        .HasColumnType("double precision")
                        .HasColumnName("base_rate");

                    b.Property<string>("EfJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ef");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("emission_compounds");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EnvironmentObject", b =>
                {
                    b.Property<int>("IdObject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_object");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObject"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<double?>("TotalMass")
                        .HasColumnType("double precision")
                        .HasColumnName("total_mass");

                    b.Property<double?>("TotalVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("total_volume");

                    b.HasKey("IdObject");

                    b.ToTable("objects");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_event");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvent"));

                    b.Property<Polygon>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("coordinates");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdEvent");

                    b.ToTable("events");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EventObject", b =>
                {
                    b.Property<int>("IdEventObject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_event_object");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEventObject"));

                    b.Property<string>("ComponentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("component_type");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("KKat")
                        .HasColumnType("numeric")
                        .HasColumnName("k_kat");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.HasKey("IdEventObject");

                    b.HasIndex("EventId");

                    b.HasIndex("ObjectId");

                    b.ToTable("event_objects");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.IndexingCoefficient", b =>
                {
                    b.Property<int>("IdIndexingCoefficient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_indexing_coefficient");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndexingCoefficient"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("numeric")
                        .HasColumnName("coefficient");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer")
                        .HasColumnName("quarter");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("IdIndexingCoefficient");

                    b.ToTable("indexing_coefficients");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaterial"));

                    b.Property<decimal?>("BaseRate")
                        .HasColumnType("numeric")
                        .HasColumnName("base_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmissionCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emission_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SubstanceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("substance_type");

                    b.Property<double?>("ToxicityFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("toxicity_factor");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("IdMaterial");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.ObjectMaterial", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("IdObjectMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("id_object_material");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision")
                        .HasColumnName("mass");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("RecoveredQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("recovered_quantity");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("ObjectId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("object_materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Specialist", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("FieldOfExpertise")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field_of_expertise");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("IdUser");

                    b.ToTable("specialists");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.WasteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EwcCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ewc_code");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<bool>("IsCombustible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_combustible");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hazardous");

                    b.Property<double>("MorphSum")
                        .HasColumnType("double precision")
                        .HasColumnName("morph_sum");

                    b.Property<string>("MorphologyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("morphology");

                    b.Property<double>("TotalMassTonnes")
                        .HasColumnType("double precision")
                        .HasColumnName("total_mass_tonnes");

                    b.HasKey("Id");

                    b.ToTable("waste_types");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.DamageEvaluation", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Event", "Event")
                        .WithMany("DamageEvaluations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EventObject", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Event", "Event")
                        .WithMany("EventObjects")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.EnvironmentObject", "Object")
                        .WithMany("EventObjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.ObjectMaterial", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.EnvironmentObject", "EnvironmentObject")
                        .WithMany("ObjectMaterials")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentObject");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Specialist", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.User", "User")
                        .WithOne("Specialist")
                        .HasForeignKey("ŽVPAIS_API.Models.Specialist", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EnvironmentObject", b =>
                {
                    b.Navigation("EventObjects");

                    b.Navigation("ObjectMaterials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Event", b =>
                {
                    b.Navigation("DamageEvaluations");

                    b.Navigation("EventObjects");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.User", b =>
                {
                    b.Navigation("Specialist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
